### ISSUE TITLE
Help with installing Marlin-renderer

### ISSUE THREAD

**Issue by justinjngan** [bourgesl/marlin-renderer#45]
Hi, 

I am trying to switch my OpenJDK to use the Marin-renderer.  I have downloaded the file marlin-0.9.4.5-Unsafe-OpenJDK11.jar. My OpenJDK version is: 11.0.12. 

When I enter the command: 
java --patch-module java.desktop=/home/bitnami/geoserver/webapps/geoserver/WEB-INF/lib/marlin-0.9.4.5-Unsafe-OpenJDK11.jar 

I get: 
The man page for the java command. 

Yes, I am probably doing something silly or missing something important due to my being quite the noob.  Got to start somewhere I guess.

Can someone please help me understand how to get this working please ?

**Comment by bourgesl** [comment]
Hi,

This command line looks correct for linux but you should add geoserver args too:
java --patch-module java.desktop=... ...
You removed the end!

Hope it helps,
Stay tuned, new marlin renderer releases for xmas !

**Comment by bourgesl** [comment]
Are you on *nix or windows ?

**Comment by justinjngan** [comment]
Linux :-) 

So for the benefit of others in the future ... geoserver universal binary runs using Jetty and has a startup.sh shell script that looks for marlin*.jar in the lib folder.  

I believe the easiest way to configure the new marlin renderer is to a) rename the old marlin renderer to something like old_*.jar or marlin*.bkp and just drop in the new jar to the lib directory.  The shell script will find the new .jar and use it as it launches Jetty (which runs the openjdk).  

Cheers!

**Comment by justinjngan** [comment]
Thank you for your help!  And what's coming ? Do tell !

**Comment by bourgesl** [comment]
Great you figured out the problem: multiple marlin jars in boot or classpath. As jdk11 provides marlin, only 1 marlin jar must be loaded by boot class path or module patch.

I will make release 0.9.4.5 b2 or 0.9.4.6 (minor tuning):
- Fixed clipper to deal with huge coords (up to 1E15)
- Fixed extra stroke joins due to dasher, clipper, or curve monotonizer
- New optimized draw joins: small mitter or round joins are ignored: 99% done
- New properties to diagnose, tune java2d pipeline
- new: tune again the curve DDA to minimize the number of generated segments vs quality! Small loss but not visible by humans (delta < 1/16th on luma)

Coming soon...

**Comment by bourgesl** [comment]
I will close the bug once release done.

**Comment by unixguru2k** [comment]
Hi @bourgesl 

Having an issue on trying to set it up for a dropwizard app.

Uses openjdk 17.0

Screenshot below 
<img width="1237" alt="Screen Shot 2021-12-31 at 5 20 12 PM" src="https://user-images.githubusercontent.com/117231/147842156-afe668b0-710a-4f18-bcc4-3452fb45066b.png">

When i try to run this on my local box, it doesn't detect Marlin Renderer.

I am sure i am doing something silly in configuration

Any help / suggestion would be appreciated, good sir.

Cheers
HD

**Comment by bourgesl** [comment]
Probably you need to give the full absolute path in module-path:
lib/marlin...
To
/home/user/... /lib/marlin...

This is not a support forum for intellij idea I do not know well.

**Comment by bourgesl** [comment]
Inactive
